# Site settings
title: CSSconf.org
email: contact@cssconf.eu
description: "CSSconf is a conference dedicated to the designers, developers and engineers who build the worldâ€™s most engaging user interfaces. From the community, for the community."
baseurl: "cssconf.org/"
url: "http://cssconf.org"
twitter_username: cssconf
github_username:  cssconf

# Build settings
markdown: kramdown
permalink: pretty
